language: python

python:
  -"3.7"

env:
  matrix:
    - TOXENV=check
    - TOXENV=python3.7

before_install:
  - python --version
  - pip --version
  - uname -a
  - lsb_release -a

install:
  - pip install -r requirements.txt
  - pip install tox
  - pip freeze

script:
  - tox -v

notifications:
  slack: smg-developers:C159xyN1rHLQKpg2gRVrDiwM
